export global Hyprland {
    pure callback change_workspace(int);
}
export global HardwareMonitor {
    in-out property <string> used_memory;
    in-out property <string> totalmemory;
    in-out property <string> cpu_usage;
    in-out property <string> network_up;
    in-out property <string> network_down;
}
export component Workspace inherits Rectangle {
    height: 34px;
    width: self.height;
    in-out property <int> id;
    in-out property text<=> txt.text;
    in-out property <color> inactive_color;
    in-out property <color> hover_color;
    background: touch.has-hover ? hover-color : inactive-color;
    txt := Text {
        color: white;
        font-size: 16px;
    }
    touch := TouchArea {
        clicked => {
            Hyprland.change-workspace(root.id);
        }
    }
}
export component MainUi inherits Window {
    preferred-width: 1920px;
    preferred-height: 40px;
    background: #1E1F29;
    in property <[{id:int, color:color, hover_color:color}]> workspaces;
    in property time<=> Clock.text;
    HorizontalLayout {
        y: 3px;
        spacing: 5px;
        for workspace in root.workspaces: Workspace {
            text: workspace.id;
            id: workspace.id;
            inactive-color: workspace.color;
            hover-color: workspace.hover_color;
        }
    }
    Clock := Text {
        color: white;
        font-size: 17px;
        x: root.width / 2 - self.width / 2;
    }
    Hw := HorizontalLayout {
        alignment: end;
        spacing: 20px;
        padding: 10px;
        Text {
            font-size: 16px;
            color: whitesmoke;
            text: "Cpu:\{HardwareMonitor.cpu-usage}";
        }
        Text {
            font-size: 16px;
            color: whitesmoke;
            text: "Mem:\{HardwareMonitor.used-memory}/\{HardwareMonitor.totalmemory}";
        }
        Text {
            font-size: 16px;
            color: whitesmoke;
            width: 100px;
            text: "Up: \{HardwareMonitor.network-up}";
        }
        Text {
            font-size: 16px;
            width: 140px;
            color: whitesmoke;
            text: "Down: \{HardwareMonitor.network-down}";
        }
    }
}
