[package]
name = "hyprland_workspaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
embargo_workspace = { version = "0.1.0", path = "../embargo_workspace" }
hyprland = "0.3.4"
